SET (Boost_USE_MULTITHREADED ON)
IF (WIN32 AND SLON_ENGINE_3RD_PARTY_FOUND)
    SET (Boost_USE_STATIC_LIBS ON)
ELSE (WIN32 AND SLON_ENGINE_3RD_PARTY_FOUND)
    SET (Boost_USE_STATIC_LIBS OFF)
ENDIF (WIN32 AND SLON_ENGINE_3RD_PARTY_FOUND)

# find packages
FIND_PACKAGE ( Boost 1.45.0 	REQUIRED	COMPONENTS signals thread unit_test_framework system filesystem iostreams)
FIND_PACKAGE ( SDL              REQUIRED )
FIND_PACKAGE ( Doxygen )
FIND_PACKAGE ( Bullet  )

IF (NOT XMLPP_CONFIGURE_INTRUSIVE)
	FIND_PACKAGE ( XML++        REQUIRED )
ENDIF (NOT XMLPP_CONFIGURE_INTRUSIVE)

IF (NOT SIMPLE_GL_CONFIGURE_INTRUSIVE)
	FIND_PACKAGE ( SimpleGL     REQUIRED )
ENDIF (NOT SIMPLE_GL_CONFIGURE_INTRUSIVE)

# Pretty plots
FIND_PACKAGE ( Gnuplot )